version: '3'
services:
  # Build MongoDB on server. Ensure .env point to this address
  mongodatabase:
    image: mongo:latest
    container_name: 'mongobackup'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
      - 27018:27018
    networks:
      - backend
  # Build Nginx on server. Ensure have certificates on config files.  Modify URLs on Nginx conf
  visualsearchapi:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodatabase
    links:
      - mongodatabase
    networks:
      - backend
      - frontend
networks:
  backend:
  frontend:
