version: '2.3'
services:
    mongodatabase:
        image: mongo:latest
        container_name: "mongobackup"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
          - 27017:27017
          - 27018:27018
    visualsearchapi:
        build: .
        ###environment:
        ###  - MONGODB_URL=mongodb://mongodatabase:27017
        ports:
          - 8080:8080
        depends_on:
          - mongodatabase
        links:
          - mongodatabase
